version: '3'
services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./src:/var/www/
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/logs:/var/log/nginx

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: data
      MYSQL_USER: test
      MYSQL_PASSWORD: secret 
    volumes:
      - ./Docker/mysql:/var/lib/mysql
    command: 
      - --default-authentication-plugin=mysql_native_password

  php-fpm:
    build: 
      context: ./Docker/php-fpm
    volumes:
      - ./src:/var/www
      - ./Docker/app/php.ini:/usr/local/etc/php/custom.d


 